"""Users model update

Revision ID: ad8d3372ce93
Revises: 21f22e3fe824
Create Date: 2025-04-22 06:47:22.877505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8d3372ce93'
down_revision: Union[str, None] = '21f22e3fe824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('open_to_collab', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'open_to_collab')
    op.drop_column('users', 'description')
    # ### end Alembic commands ###
