"""Projects updated

Revision ID: bdb9f0301d59
Revises: a6fd6ec328b3
Create Date: 2025-03-17 22:20:29.918362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb9f0301d59'
down_revision: Union[str, None] = 'a6fd6ec328b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'group_id')
    # ### end Alembic commands ###
